export const ADD_ITEM_TO_CART_REQUEST = "ADD_ITEM_TO_CART_REQUEST"
export const ADD_ITEM_TO_CART_SUCCESS = "ADD_ITEM_TO_CART_SUCCESS"
export const ADD_ITEM_TO_CART_FAIL = "ADD_ITEM_TO_CART_FAIL"


export const GET_CART_REQUEST="GET_CART_REQUEST"
export const GET_CART_SUCCESS="GET_CART_SUCCESS"
export const GET_CART_FAIL="GET_CART_FAIL"

export const REMOVE_CART_ITEM_REQUEST="REMOVE_CART_ITEM_REQUEST"
export const REMOVE_CART_ITEM_SUCCESS="REMOVE_CART_ITEM_SUCCESS"
export const REMOVE_CART_ITEM_FAIL="REMOVE_CART_ITEM_FAIL"

export const UPDATE_CART_ITEM_REQUEST="UPDATE_CART_ITEM_REQUEST"
export const UPDATE_CART_ITEM_SUCCESS="UPDATE_CART_ITEM_SUCCESS"
export const UPDATE_CART_ITEM_FAIL="UPDATE_CART_ITEM_FAIL"

export const CLEAR_ERROR = "CLEAR_ERROR";