export const   FIND_PRODUCT_BY_ID_REQUEST  = "FIND_PRODUCT_BY_ID_REQUEST";
export const  FIND_PRODUCT_BY_ID_SUCCESS = "FIND_PRODUCT_BY_ID_SUCCESS";
export const  FIND_PRODUCT_BY_ID_FAIL = "FIND_PRODUCT_BY_ID_FAIL";

export const  FIND_PRODUCT_BY_CATEGORY_REQUEST = "FIND_PRODUCT_BY_CATEGORY_REQUEST";
export const  FIND_PRODUCT_BY_CATEGORY_SUCCESS = "FIND_PRODUCT_BY_CATEGORY_SUCCESS";
export const  FIND_PRODUCT_BY_CATEGORY_FAIL = "FIND_PRODUCT_BY_CATEGORY_FAIL";
 
 
export const CLEAR_ERROR = "CLEAR_ERROR";